# Generated by Django 5.1.5 on 2025-02-01 16:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeFAQ', '0002_remove_faq_question_bn_remove_faq_question_hi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='translations',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
