# Generated by Django 5.1.5 on 2025-02-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeFAQ', '0004_faq_answer_es_faq_question_es'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_es',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_es',
        ),
    ]
